@startuml
!theme blueprint

package Lint {

class FullStopNewline{
Adds newline characters to fullstops.
--
**Functions**
+NewLiner() -> string
--
**Imports**
"strings"
}

class Indentation{
Function to be called for from main
--
**Functions**
+EnviromentIndentation([]string) -> []string
--
**Imports**
"fmt"
"strings"
}
}


map settings {
	NewLineFullStop => bool
	IndentTabs => bool
	IndentSpaces => int
	Indentation => bool
	FormatComments => bool
	CommentTabs => bool
	CommentSpaces => int
}


class main {
Main file and main function
--
**Functions**
IsError() -> bool
--
**Imports**
Lint "LatexLinter/pkg"
"encoding/json"
"fmt"
"io/ioutil"
"os"
"strings"
}



note top of main : Main file that calls all functions.

object TexFile
object LintedFile
settings "JSON_FILE"--"Struct" main
main <|.. Indentation
TexFile --|> main : new texFile goes through main
main --|> LintedFile : Linted file saves on CWD
main <|.. FullStopNewline
@enduml
