@startuml
!theme blueprint

package Lint {

class FullStopNewline{
Adds newline characters to fullstops.
--
**Functions**
+NewLiner() -> string
--
**Imports**
"strings"
}

class Indentation{
Function to be called for from main
--
**Functions**
+EnviromentIndentation([]string) -> []string
-starter() -> bool
-ender() -> bool
--
**Imports**
"fmt"
"strings"
}

class commentFormater {
 Adds specific spacers to comments
--
**Imports**
"strings"
**Functions**
+CommentFormat() -> string
}

}


class WriteToNewFile {
Writes file-lines to file copy.
--
**Functions**
+CreateAndWriteNewFile(...) -> bool
-fileExist(filepath) -> bool
**Imports**
"errors"
"fmt"
"log"
"os"
"strconv"
"strings"
}

map settings {
	NewLineFullStop => bool
	IndentTabs => bool
	IndentSpaces => int
	Indentation => bool
	FormatComments => bool
	CommentTabs => bool
	CommentSpaces => int
}


class main {
Main file and main function
--
**Functions**
IsError() -> bool
--
**Imports**
Lint "LatexLinter/pkg"
"encoding/json"
"fmt"
"io/ioutil"
"os"
"strings"
}



note top of main : Main file that calls all functions.

object TexFile
object LintedFile
settings "JSON_FILE"--"Struct" main
main <|.. Indentation
main <|.. commentFormater
main <|.. WriteToNewFile
TexFile --|> main : new texFile goes through main
main --|> LintedFile : Linted file saves on CWD
main <|.. FullStopNewline
@enduml
